---
# defaults file for create_LVM_Dis
 
  key_1: "/root/.ssh/id_rsa.pub"

  package:
  - lvm2
  - mc
  - tree
  - tmux
  state: present

  list_name:
  - "Vasy"
  - "Pety"
  - "Masha"

  part: "1"             # Количество разделов на диске

  drive1: "/dev/sdb"    # Диски
  drive2: "/dev/sdc"
  drive3: "/dev/sdd"
    
  fs_type: "ext4"       # Файловая система

  vgroup: "/dev/vg1/lv1"
  mount: "/mnt/data"     # Точки монтирования

